name: bard_tilt
channels:
  - conda-forge
dependencies:
  - hdbscan
  - numpy
  - pip
  - matplotlib
  - pandas
  - scipy
  - xarray
  - zarr
  - tqdm
  - umap-learn
  - scikit-learn
  - seaborn
  - colorcet
  - sunpy
  - ipywidgets
